version: "3.1"
services:
  streamer:
    build:
      context: ./streamer
    env_file:
      - ./.env
    environment:
      DB_HOST: db
    volumes:
      - ./streamer:/app
    depends_on:
      - db

  api:
    build:
      context: ./api
    env_file:
      - ./.env
    environment:
      DB_HOST: db
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
#      - ./initialize.sql:/docker-entrypoint-initdb.d/initialize.sql

volumes:
  db-data: